#!/usr/sbin/nft -f

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        # Let responses to your own connections come back (like SSH replies)
        ct state established,related accept

        # Allow loopback interface (lo)
        iif lo accept

        # Accept TCP port 22 only from VPN client
        ip saddr 10.200.0.2 tcp dport 22 accept

        # Allow ICMP (ping)
        icmp type echo-request accept

        # WireGuard VPN
        udp dport 51820 accept
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;

        iif wg0 accept
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}


table ip nat {

    chain postrouting {
        type nat hook postrouting priority 100;
        masquerade
    }
}
