/*
==================================================================
HEALTHBANE PHISHING PDF RULE (FIXED FOR REAL SAMPLES)
==================================================================

Key observation from samples:
- Phishing PDFs contain /URI annotations
- Multiple embedded links per document
- Credential paths: verify, login, portal, pay, enroll
- Some documents generated by wkhtmltopdf 0.12.6
- Clean invoices still contain PDFs but fewer phishing patterns

We focus on STRUCTURE + LINK PATTERNS, not fake text.
==================================================================
*/

rule HEALTHBANE_Phishing_PDF
{
    meta:
        author = "Ramazan Mustafayev"
        description = "Detect HEALTHBANE phishing PDFs using embedded link structure and credential paths"
        reference = "HEALTHBANE campaign 4x00 analysis"
        threat_level = "HIGH"
        confidence = "HIGH"
        date = "2026-05-20"

    strings:

        /*
        PDF signature
        */
        $pdf = "%PDF"

        /*
        PDF link annotation structure (VERY IMPORTANT in samples)
        */
        $annot = "/Annots"
        $uri = "/URI"

        /*
        Credential harvesting URL paths observed in dataset
        */
        $verify = "/verify"
        $login  = "/login"
        $portal = "/portal"
        $enroll = "/enroll"
        $pay    = "/pay"

        /*
        Phishing-style query parameters (observed in sample 3)
        */
        $token = "token="
        $id    = "id="

        /*
        Strong signal: wkhtmltopdf phishing generator (only in malicious sample)
        */
        $wkhtml = "wkhtmltopdf 0.12.6"

    condition:

        /*
        Must be a PDF
        Must contain link structure (/Annots + /URI)
        Must contain at least 2 phishing indicators from URLs
        AND either wkhtmltopdf OR multiple credential paths
        */

        $pdf at 0 and
        $annot and
        $uri and

        2 of (
            $verify,
            $login,
            $portal,
            $enroll,
            $pay,
            $token,
            $id
        )
        and

        (
            $wkhtml or
            3 of ($verify, $login, $portal, $enroll, $pay)
        )
}

/*
==================================================================
TEST EXPECTATION (FROM samples_manifest.txt)

TRUE POSITIVES:
- phishing_sample.pdf
- healthbane_lure_02.pdf
- healthbane_invoice_08991.pdf (wkhtml + pay + login)

TRUE NEGATIVES:
- clean_invoice.pdf
- benign_invoice.pdf
==================================================================
*/
